version: '3.7'
services:
  web:
    build: ./docker/web
    ports:
      - 8000:80
    volumes:
      - ./php:/var/www/html
  db:
    image: mysql:8.0.19
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=registerForm
      - TZ='Asia/Tokyo'
    ports:
      - 3309:3306
    volumes:
      - ./docker/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - data:/var/lib/mysql

volumes:
  data: